# Generated by Django 5.2.8 on 2025-11-30 23:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(unique=True, verbose_name="Telegram ID"),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Username"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Имя"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Фамилия"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "can_manage_applications",
                    models.BooleanField(
                        default=True, verbose_name="Может управлять заявками"
                    ),
                ),
                (
                    "can_manage_prices",
                    models.BooleanField(
                        default=False, verbose_name="Может управлять ценами"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram администратор",
                "verbose_name_plural": "Telegram администраторы",
            },
        ),
        migrations.CreateModel(
            name="HairApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "length",
                    models.CharField(
                        choices=[
                            ("40-50", "40-50 см"),
                            ("50-60", "50-60 см"),
                            ("60-70", "60-70 см"),
                            ("70-80", "70-80 см"),
                            ("80-90", "80-90 см"),
                            ("90-100", "90-100 см"),
                            ("100+", "Более 100 см"),
                        ],
                        max_length=10,
                        verbose_name="Длина волос",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("blonde", "Блонд (светлые)"),
                            ("light", "Светло-русые"),
                            ("medium", "Русые"),
                            ("dark", "Темно-русые"),
                            ("brown", "Темные (каштановые)"),
                        ],
                        max_length=20,
                        verbose_name="Цвет волос",
                    ),
                ),
                (
                    "structure",
                    models.CharField(
                        choices=[
                            ("thin", "Славянка (тонкие)"),
                            ("medium", "Средние"),
                            ("thick", "Густые"),
                        ],
                        max_length=20,
                        verbose_name="Структура волос",
                    ),
                ),
                (
                    "age",
                    models.CharField(
                        choices=[
                            ("child", "Детские (до 14 лет)"),
                            ("adult", "Взрослые (14+ лет)"),
                        ],
                        max_length=20,
                        verbose_name="Возраст",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("natural", "Натуральные (не окрашенные)"),
                            ("dyed", "Окрашенные"),
                            ("perm", "После химической завивки"),
                        ],
                        max_length=20,
                        verbose_name="Состояние волос",
                    ),
                ),
                (
                    "photo1",
                    models.ImageField(
                        help_text="Обязательное",
                        upload_to="hair_photos/%Y/%m/%d/",
                        verbose_name="Фото 1",
                    ),
                ),
                (
                    "photo2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="hair_photos/%Y/%m/%d/",
                        verbose_name="Фото 2",
                    ),
                ),
                (
                    "photo3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="hair_photos/%Y/%m/%d/",
                        verbose_name="Фото 3",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Город"),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительная информация от продавца",
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "estimated_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Рассчитанная автоматически",
                        max_digits=10,
                        verbose_name="Предварительная стоимость",
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Устанавливается администратором",
                        max_digits=10,
                        null=True,
                        verbose_name="Итоговая стоимость",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("viewed", "Просмотрена"),
                            ("accepted", "Принята"),
                            ("rejected", "Отклонена"),
                            ("completed", "Завершена"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Заметки администратора"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Заявка на продажу",
                "verbose_name_plural": "Заявки на продажу",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="hair_app_ha_created_0d3070_idx"
                    ),
                    models.Index(
                        fields=["status"], name="hair_app_ha_status_938357_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PriceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "length",
                    models.CharField(
                        choices=[
                            ("40-50", "40-50 см"),
                            ("50-60", "50-60 см"),
                            ("60-70", "60-70 см"),
                            ("70-80", "70-80 см"),
                            ("80-90", "80-90 см"),
                            ("90-100", "90-100 см"),
                            ("100+", "Более 100 см"),
                        ],
                        max_length=10,
                        verbose_name="Длина",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("blonde", "Блонд (светлые)"),
                            ("light", "Светло-русые"),
                            ("medium", "Русые"),
                            ("dark", "Темно-русые"),
                            ("brown", "Темные (каштановые)"),
                        ],
                        max_length=20,
                        verbose_name="Цвет",
                    ),
                ),
                (
                    "structure",
                    models.CharField(
                        choices=[
                            ("thin", "Славянка (тонкие)"),
                            ("medium", "Средние"),
                            ("thick", "Густые"),
                        ],
                        max_length=20,
                        verbose_name="Структура",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("natural", "Натуральные (не окрашенные)"),
                            ("dyed", "Окрашенные"),
                            ("perm", "После химической завивки"),
                        ],
                        max_length=20,
                        verbose_name="Состояние",
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Базовая цена",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Позиция прайс-листа",
                "verbose_name_plural": "Прайс-лист",
                "unique_together": {("length", "color", "structure", "condition")},
            },
        ),
    ]
